### ISSUE TITLE
Good mod, good Job

### ISSUE THREAD

**Issue by 0razec** [Dong-Wo-Long/BetterDuStryMod#1]
Greetings, I have to say... this mod is very impressive, the fact that the units are so well crafted makes me anxious when I get to Erekir's T5, but I'm patient. Also, you are a great role model for me who wants to merge Mods. Thanks!

**Comment by Dong-Wo-Long** [comment]
Thanks for the feedback :)
Despite the fact that I still haven't finished Serpulo, there will be a major update for Erekir in the near future. I want to take a bit of a break from reworking Serpulo content.
