### ISSUE TITLE
Nova weapons are vanilla?

### ISSUE THREAD

**Issue by Lilcat731** [Dong-Wo-Long/BetterDuStryMod#2]
the new update is great, but the nova laser cannons seem unchanged from their vanilla counterparts, not sure if its a bug or intended. I also liked the horizon helicopter but understand why it was changed, so maybe make the horizon heli a seperate unit?

**Comment by Dong-Wo-Long** [comment]
Oh no...

**Comment by Dong-Wo-Long** [comment]
> I also liked the horizon helicopter but understand why it was changed, so maybe make the horizon heli a seperate unit?

I guess that's what I'll do. After all, not everyone liked that decision

**Comment by Dong-Wo-Long** [comment]
> the new update is great, but the nova laser cannons seem unchanged from their vanilla counterparts, not sure if its a bug or intended.

Well, I think I've fixed that. If you notice anything else like that, please let me know right away

**Comment by Lilcat731** [comment]
uhh as of now all of the weapons are vanilla now which led to some pretty funky things
![image_2024-08-11_141326762](https://github.com/user-attachments/assets/be5d6685-8782-4eaf-ba67-0d1bb58806b5)
the turrets are fine and the unit HP/Armor is fine, its just their weapons which are wack

**Comment by Dong-Wo-Long** [comment]
Sorry, Lilcat, something personal happened and I don't really want to update the mod right now. I don't know much English unfortunately, but if you need me, look for me in discord (my nickname: λ )

**Comment by Lilcat731** [comment]
ah thats fine, you can work on this whenever you want, I'm fine with that.

**Comment by Dong-Wo-Long** [comment]
Thanks, Lilcat. Write if anything happens

**Comment by Dong-Wo-Long** [comment]
I fixed the bug with vanilla units - shouldn't be there now. Also, the sounds at Serpulo's turrets should have appeared
