### ISSUE TITLE
Game crashes when Avert unit appears

### ISSUE THREAD

**Issue by Zeins-II** [Dong-Wo-Long/BetterDuStryMod#3]
https://github.com/user-attachments/assets/1074f7d9-b985-48c9-94a9-98cced6455ae

@Dong-Wo-Long 
Once that unit appears, the game crashes immediately regardless of whether it is from an enemy or an ally.I hope you fix it soon.🙏🙏

**Comment by Dong-Wo-Long** [comment]
Oh, I'm sorry that I'm only answering now - I'll try to fix it soon...

**Comment by Zeins-II** [comment]
I love your mod so much! By the way, can you teach me how to make mods like this? I have crazy mod ideas.☺️

**Comment by Zeins-II** [comment]
> Tôi rất thích bản mod của bạn! Nhân tiện, bạn có thể hướng dẫn tôi cách tạo bản mod như thế này không? Tôi có những ý tưởng mod điên rồ.☺️
You will love it for sure.

**Comment by Dong-Wo-Long** [comment]
> and you too!

I'm sorry, I have to say no, I'm not interested in men.

**Comment by Dong-Wo-Long** [comment]
And you're just in time, the issue with this unit has been temporarily resolved (at the moment it has simply ceased to exist)

**Comment by Zeins-II** [comment]
Hehe I guess so, thanks for the reply anyway. 
Have a nice day man.Guess I have to learn mods myself even though I have no idea how.

**Comment by Zeins-II** [comment]
Wait... What do you mean when you say you're not interested in men... I'm confused.

**Comment by Dong-Wo-Long** [comment]
> Guess I have to learn mods myself even though I have no idea how.

It's not difficult. Just rely on my mod and take a look from time to time - about the units and all the towers have everything that I have written (if you work with json/hjson)

**Comment by Dong-Wo-Long** [comment]
I can't teach you Java, I'm sorry, but it's not for me.

**Comment by Zeins-II** [comment]
Okay~
Have a nice day man.
